name: Build and Test
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@main
        with:
          node-version: 16.13.1
      - name: Build, lint and test
        run: |
          yarn
          yarn test --watch=false --browsers=ChromeHeadless
          yarn build --prod
